spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id:  true

  config:
    enabled:  false
    uri:  http://localhost:8888

  server:
    port: 8780

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/